//DROP TABLE if exists mpa;
//drop table if exists film;


CREATE TABLE IF NOT EXISTS user_table (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar,
login varchar,
name varchar,
birthday date
);

CREATE TABLE IF NOT EXISTS likes (
film_id INTEGER,
user_id INTEGER,
primary key (film_id, user_id));


CREATE TABLE IF NOT EXISTS genre (
genre_id INTEGER NOT NULL PRIMARY KEY ,
name varchar
);

MERGE INTO genre (genre_id, name)
    VALUES (1, 'Комедия'),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');


CREATE TABLE IF NOT EXISTS films_genres (
film_id INTEGER,
genre_id INTEGER,
primary key (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS mpa (
mpa_id INTEGER NOT NULL PRIMARY KEY ,
name varchar
);

MERGE INTO mpa (mpa_id, name) VALUES
(1, 'G'),
(2, 'PG'),
(3, 'PG-13'),
(4, 'R'),
(5, 'NC-17');

CREATE TABLE IF NOT EXISTS friends(
user_id INTEGER,
friend_id INTEGER,
primary key (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS film (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
description varchar,
release_date date,
duration INTEGER,
mpa_id INTEGER
);